# Generated by Django 3.2.7 on 2025-01-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartRequestsMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campis_request', models.CharField(max_length=80, unique=True)),
                ('request_amount', models.IntegerField(db_index=True, default=1)),
                ('fake', models.BooleanField(default=False)),
            ],
        ),
    ]
