# Generated by Django 3.2.7 on 2025-01-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartrequestsmemory',
            name='fake',
        ),
    ]
