# Generated by Django 3.2.7 on 2025-02-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_chartrequestsmemory_fake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartrequestsmemory',
            old_name='campis_request',
            new_name='instituicoes_request',
        ),
    ]
