# Generated by Django 3.2.7 on 2025-02-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_campis_request_chartrequestsmemory_instituicoes_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartrequestsmemory',
            name='instituicoes_request',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
